### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by claytondaley** [npinger/base-crm-api-client#1]
Quick suggestion to put some kind of license on this.  Anyone trying to legitimately use it will need an explicit licensing statement.

Some examples for API Clients are:
- Apache (Google, https://code.google.com/p/google-api-java-client/)
- LGPL (MaxMind, https://github.com/maxmind/GeoIP2-python/blob/master/LICENSE)
- BSD 3-clause (PiwikTracker by Piwik, https://github.com/piwik/piwik/blob/master/libs/PiwikTracker/LICENSE.txt)

If you don't care to be explicitly cited in derivative works, you could use a public domain statement more like http://unlicense.org/

**Comment by npinger** [comment]
Thanks for the suggestion @claytondaley 

I've added a License file - Apache 2.0. Feel free to use as you wish under that license.
